# Generated by Django 3.0.5 on 2020-05-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_name',
        ),
    ]
